version: "3.8"

services:
  backend:
    build: ./
    ports:
      - '80:80'
    volumes:
      - backend_vol:/app
      - ./:/app
      - /app/node_modules # Skip replacing this folder

volumes:
  backend_vol:
