version: "3.8"

services:
  backend:
    build: ./
    volumes:
      - backend_vol:/app
      - ./:/app
      - /app/node_modules # Skip replacing this folder
    environment:
      REDIS_URL: redis://redis:6379 # Connection string to Redis
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379" # Expose Redis port

volumes:
  backend_vol:
