version: "3.8"

services:
  backend:
    build: ./
    ports:
      - '80:80'
    depends_on:
      - 'postgres'
    volumes:
      - backend_vol:/app
      - ./:/app
      - /app/node_modules # Skip replacing this folder

  postgres:
    image: postgres:14-alpine
    ports:
      - 5435:5432
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_database

volumes:
  backend_vol:
  postgres_vol:
